name: Snyk Multi-Language Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-security-scan:
    name: Run Snyk SCA Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for JS/TS)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Java (for Java/Kotlin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Test - Python
        run: snyk test --file=requirements.txt || true
        continue-on-error: true

      - name: Snyk Test - JavaScript/TypeScript
        run: snyk test --file=package.json || true
        continue-on-error: true

      - name: Snyk Test - Java/Kotlin
        run: snyk test --file=pom.xml || snyk test --file=build.gradle || true
        continue-on-error: true

      - name: Snyk Test - Go
        run: snyk test --file=go.mod || true
        continue-on-error: true

      - name: Snyk Test - Swift, Objective-C, Shell (fallback scan)
        run: snyk test || true
        continue-on-error: true
